import fs from 'node:fs'

export const prependGeneratedFile = async ({ path }: { path: string }) => {
  const comment = `/**
 * NOTICE:
 * This file is generated and managed programmatically by Innate.
 * Do not edit this file directly. Edits to this file will be overwritten.
 */
`

  const fileContent = fs.readFileSync(path, 'utf-8')

  fs.writeFileSync(path, `${comment}\n${fileContent}`)
}
