import fs from 'node:fs'
import path from 'node:path'

export const addGeneratedComment = async () => {
  const schemaPath = path.join(import.meta.dir, '../../../../schema.prisma')
  const comment = `// *************************************************************************************************
// NOTICE:
// 
// This schema.prisma is generated by the Prisma CLI and managed programmatically by Innate.
// Do not edit this file directly. Edits to this file will be overwritten.
// *************************************************************************************************\n`

  const prismaSchema = fs.readFileSync(schemaPath, 'utf-8')

  fs.writeFileSync(schemaPath, `${comment}\n${prismaSchema}`)
}
